name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Verify version matches manifest
      run: |
        MANIFEST_VERSION=$(jq -r '.version' src/manifest.json)
        if [ "$MANIFEST_VERSION" != "${{ steps.get_version.outputs.VERSION }}" ]; then
          echo "Version mismatch: manifest.json has $MANIFEST_VERSION but tag is ${{ steps.get_version.outputs.VERSION }}"
          exit 1
        fi
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run linter
      run: npm run lint
    
    - name: Build extension
      run: npm run build
    
    - name: Package extension
      run: npm run package
    
    - name: Sign and publish to Firefox Add-ons
      env:
        WEB_EXT_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
      run: |
        mkdir -p artifacts
        npx web-ext sign \
          --source-dir=dist \
          --artifacts-dir=artifacts \
          --api-key=$WEB_EXT_API_KEY \
          --api-secret=$WEB_EXT_API_SECRET
    
    - name: Create Release Notes
      id: release_notes
      run: |
        echo "## What's Changed" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md || echo "First release" >> RELEASE_NOTES.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*.xpi
          dist/strava-vam-extension-v*.zip
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-artifacts
        path: |
          artifacts/*.xpi
          dist/*.zip
        retention-days: 30
