name: Build and Release (Auto-Submit to AMO)

on:
  push:
    tags:
      - 'v*.*.*'
      # Exclude manual release tags (those ending with -manual)
      - '!v*.*.*-manual'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Verify version matches manifest
      run: |
        MANIFEST_VERSION=$(jq -r '.version' src/manifest.json)
        if [ "$MANIFEST_VERSION" != "${{ steps.get_version.outputs.VERSION }}" ]; then
          echo "Version mismatch: manifest.json has $MANIFEST_VERSION but tag is ${{ steps.get_version.outputs.VERSION }}"
          exit 1
        fi
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run linter
      run: npm run lint
    
    - name: Build extension
      run: npm run build
    
    - name: Package extension
      run: npm run package
    
    - name: Run package structure tests
      run: npm run test:package
    
    - name: Validate package structure
      run: npm run validate:package
    
    - name: Validate with web-ext lint
      run: npm run validate
    
    - name: Sign and publish to Firefox Add-ons
      env:
        WEB_EXT_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
      run: |
        mkdir -p artifacts
        # Automatically submit to AMO for review
        # This requires the extension to be already listed on AMO
        npx web-ext sign \
          --source-dir=dist \
          --artifacts-dir=artifacts \
          --channel=listed \
          --api-key=$WEB_EXT_API_KEY \
          --api-secret=$WEB_EXT_API_SECRET
    
    - name: Create Release Notes
      id: release_notes
      run: |
        cat > RELEASE_NOTES.md << 'EOF'
        ## 🚀 Automatic Release
        
        This release was automatically submitted to Firefox Add-ons Store for review.
        
        ### 📦 Files Included
        - **Signed .xpi**: Automatically submitted to AMO
        - **Source ZIP**: For verification and backup
        
        ### ✅ Status
        - Extension built and tested successfully
        - Signed with Mozilla credentials
        - Automatically submitted for review
        - Typically reviewed within 1-3 days
        
        ### 📚 Documentation
        - [Extension on Firefox Add-ons](https://addons.mozilla.org/firefox/addon/strava-vam-extension/)
        - [CI/CD Setup Guide](docs/CI-CD-SETUP.md)
        
        ---
        
        ## What's Changed
        EOF
        
        # Add commit history
        if git describe --tags --abbrev=0 HEAD^ 2>/dev/null; then
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md
        else
          echo "- Initial release" >> RELEASE_NOTES.md
        fi
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*.xpi
          dist/strava-vam-extension-v*.zip
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-artifacts
        path: |
          artifacts/*.xpi
          dist/*.zip
        retention-days: 30
